### ISSUE TITLE
Docker Images ?

### ISSUE THREAD

**Issue by roddersg** [jhu-ep-coursera/fullstack-course1-module1#14]
At the start of the lecture, there is a mention of Docker Images.  How do I use them and and scripts to build virtual images of the Ubuntu system?

**Comment by ejavaguy** [comment]
Docker was used to create a test image for Fedora and Ubuntu so we could provide a lesson on how to install Rails on those platforms.

Although it was not a lesson on Docker, the [scripts used were posted to this repository](https://github.com/jhu-ep-coursera/fullstack-course1-module1/tree/master/Lecture01-Installation/Linux-Installs) for those familiar with Docker and wanted a starting point.
The [Dockerfile](https://github.com/jhu-ep-coursera/fullstack-course1-module1/blob/master/Lecture01-Installation/Linux-Installs/ubuntu-devenv/Dockerfile) was used to create the image and the additional scripts were used to verify the Rails install commands used during the lesson.

There has been at least one pull request updating them since originally created in Summer of 2015. Did you have an issue using them as someone with some experience with Docker?

**Comment by roddersg** [comment]
Hi there,
Thanks for your reply.  I'm just starting to read about Docker.  However, I
gave up and build a VMimage using Ubuntu 16.04 64 Desktop.  The only
problems I had when using the scripts that followed was the installation of
PhantomJS, of which I installed the latest versions.

Rodney

**Comment by ejavaguy** [comment]
Installing the "latest" PhantomJS was a bear when the instructions were
written in Sep 2015 -- but
- a topic separate from Docker
- luckily was not necessary for courses 1-5 (1.9 binary was good enough)
- looks like they now have pre-built "latest" binaries for you to download:
  http://phantomjs.org/download.html - hurray!
- sounds like you were able to do it - double hurray!

When I did install the "latest", I
- built a Docker image exactly to their stated specs for my target OS
- built PhantonJS from the source in their git repository (took many hours)
- made that available to my target Docker image as if I had downloaded it
  form the Internet
  Sounds like that extra work is no longer necessary.

Please consider submitting a pull request with updated installation
instructions based on your experience.
thanks!

**Comment by mohammed-7** [comment]
can anyone please tell me the step advisory to follow in this module 1, im using ubuntu 16.04 and i cant able to understand how to install and what to install the files are bit confusing,

**Comment by ejavaguy** [comment]
The course lecture video lays out the steps to follow (I believe using Ubuntu 14.x) and the [scripts located in the github](https://github.com/jhu-ep-coursera/fullstack-course1-module1/tree/master/Lecture01-Installation/Linux-Installs/ubuntu-devenv) provide the step by step details. There appear to be some updates contributed specifically for 16.x.
You will need to describe your current state, which step failed, and details about the failure in order to be able to help. However, it is assumed that whichever OS you are using (Windows, MacOS, Linux, etc.) that you already understand how to do basic configuration within that OS.
The best place to get help specifically on this course is within the Coursera discussion board for course#1. There are many mentors monitoring that area.
